-- 코드를 입력하세요
SELECT B.CATEGORY, SUM(S.SALES) AS TOTAL_SALES
FROM (SELECT BOOK_ID, SUM(SALES) AS SALES
      FROM BOOK_SALES
      WHERE DATE_FORMAT(SALES_DATE, "%Y-%m") = "2022-01"
      GROUP BY BOOK_ID) AS S
INNER JOIN BOOK AS B
ON S.BOOK_ID = B.BOOK_ID
GROUP BY B.CATEGORY
ORDER BY CATEGORY;

